FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173

# Set environment variables for Nginx
ENV PORT=8080
ENV API_URL=https://wizard-trainer-backend-1042877629487.us-central1.run.app

CMD ["npm", "run", "dev"]
