version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8080
      - PRODUCTION=true
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080/api/
    restart: unless-stopped

networks:
  default:
    name: wizard-trainer-network
